### ISSUE TITLE
Cache users

### ISSUE THREAD

**Issue by froque** [premium-minds/datagrip-vault-plugin#12]
~Dbeaver~ Datagrip uses multiple connections at the same time, leading to multiple requests to Vault and multiple temporary users created. 

Additionally, this is a problem for read replica databases that may not process new users in time and reject the authentication 

 * https://developer.hashicorp.com/vault/docs/concepts/lease 
 * https://github.com/premium-minds/dbeaver-vault/issues/11

**Comment by inverse** [comment]
I've noticed this too - connecting to read replica complains as new user info not synced in time.
