### ISSUE TITLE
Revoked credentials are not cleaned 

### ISSUE THREAD

**Issue by froque** [premium-minds/datagrip-vault-plugin#19]
See https://github.com/premium-minds/dbeaver-vault/issues/17

**Comment by chinskiy** [comment]
Hello @froque ,
First of all, thank you for your work - this plugin is extremely useful!
Do you have in plans to fix this?
Faced a similar issue described at premium-minds/dbeaver-vault#17 for datagrip, and as for a workaround I can only restart IDE
